<%@page session="false" pageEncoding="utf-8"%>
<%@taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.2"%>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/core.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/x-editable.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/splitPane.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/tree.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/multiform.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/components.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/init.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/dialogs.js"></script>
<script type="text/javascript" src="/libs/composum/sling/commons/components/js/codeEditor.js"></script>
