<%@page session="false" pageEncoding="utf-8"%>
<%@taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.2"%>
<sling:call script="/libs/composum/sling/console/page/script.jsp"/>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/ace.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-json.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-xml.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-html.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-jsp.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-css.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-less.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-javascript.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-dart.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-groovy.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-java.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-scala.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-markdown.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/mode-text.js"></script>
<script type="text/javascript" src="/libs/jslibs/ace/1.1.8/theme-clouds.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/property.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/nodes.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/query.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/browser.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/properties.js"></script>
<script type="text/javascript" src="/libs/composum/sling/console/browser/js/nodeview.js"></script>
